[profile.default]
src = "src"
out = "out"
libs = ["lib"]
network = "tempo"

[rpc_endpoints]
tempo = "https://rpc.tempo.xyz/"
moderato = "https://rpc.moderato.tempo.xyz/"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
