export const GRABPO_ABI = [
  {
    type: "function",
    name: "acceptBid",
    inputs: [
      { name: "_index", type: "uint256" },
      { name: "_id", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addBid",
    inputs: [
      { name: "_index", type: "uint256" },
      { name: "_distanceD6", type: "uint128" },
      { name: "_tipD6", type: "uint128" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelBid",
    inputs: [
      { name: "_index", type: "uint256" },
      { name: "_id", type: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "escrow",
    inputs: [{ name: "", type: "bytes32" }],
    outputs: [
      { name: "owner", type: "address" },
      { name: "worker", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getActiveIndexAt",
    inputs: [{ name: "_pos", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getActiveIndicesCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEscrowAt",
    inputs: [{ name: "_pos", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getEscrowCount",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOrderAt",
    inputs: [
      { name: "_index", type: "uint256" },
      { name: "_pos", type: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getOrderCount",
    inputs: [{ name: "_index", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "judge",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "orderbook",
    inputs: [
      { name: "index", type: "uint256" },
      { name: "id", type: "bytes32" },
    ],
    outputs: [
      { name: "distanceD6", type: "uint128" },
      { name: "tipD6", type: "uint128" },
      { name: "customer", type: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "release",
    inputs: [{ name: "_id", type: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resolve",
    inputs: [
      { name: "_id", type: "bytes32" },
      { name: "_refund", type: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "BidAdded",
    inputs: [
      { name: "index", type: "uint256", indexed: true },
      { name: "id", type: "bytes32", indexed: true },
      { name: "customer", type: "address", indexed: true },
      { name: "distanceD6", type: "uint128", indexed: false },
      { name: "tipD6", type: "uint128", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BidCancelled",
    inputs: [
      { name: "index", type: "uint256", indexed: true },
      { name: "id", type: "bytes32", indexed: true },
      { name: "customer", type: "address", indexed: true },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "BidAccepted",
    inputs: [
      { name: "index", type: "uint256", indexed: true },
      { name: "id", type: "bytes32", indexed: true },
      { name: "customer", type: "address", indexed: false },
      { name: "worker", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EscrowReleased",
    inputs: [
      { name: "id", type: "bytes32", indexed: true },
      { name: "owner", type: "address", indexed: false },
      { name: "worker", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "EscrowResolved",
    inputs: [
      { name: "id", type: "bytes32", indexed: true },
      { name: "refund", type: "bool", indexed: false },
      { name: "owner", type: "address", indexed: false },
      { name: "worker", type: "address", indexed: true },
      { name: "amount", type: "uint256", indexed: false },
    ],
    anonymous: false,
  },
] as const;
